# Generated by Django 2.0.5 on 2018-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.IntegerField(default=0, primary_key='true', serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('adresss', models.CharField(max_length=100)),
                ('special_iteam', models.CharField(max_length=100)),
            ],
        ),
    ]
