# Generated by Django 2.0.5 on 2018-12-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, upload_to='res_logo'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ImageField(blank=True, upload_to='res_menu'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(default='', max_length=500),
        ),
    ]
